export const CUSTOM_I18N = {
  search: 'Tìm kiếm',
  clear: 'Xóa',
  notfound: 'Không tìm thấy emoji nào',
  skintext: 'Chọn màu da mặc định',
  categories: {
    search: 'Kết quả tìm kiếm',
    recent: 'Đã sử dụng gần đây',
    smileys: 'Mặt cười & cảm xúc',
    people: 'Mặt cười & hình người',
    nature: 'Động vật & thiên nhiên',
    foods: 'Đồ ăn & thức uống',
    activity: 'Hoạt động',
    places: 'Du lịch & địa điểm',
    objects: 'Đồ vật',
    symbols: 'Biểu tượng',
    flags: 'Cờ',
    custom: 'Tùy chỉnh',
  },
  categorieslabel: 'Danh mục',
  skintones: {
    1: 'Màu da mặc định',
    2: 'Màu da sáng',
    3: 'Màu da trung bình-sáng',
    4: 'Màu da trung bình',
    5: 'Màu da trung bình-tối',
    6: 'Màu da tối',
  },
};
